- platform: template
  lights: 
    bedroom_fan_light:
      friendly_name: "Bedroom Fan Light"
      level_template: "{{ states('input_number.bedroom_fan_light') | int }}"
      set_level:
        service: rest_command.set_bedroom_fan_light
        data:
          light_percentage: "{{ ((brightness / 255) * 100) | round(0) }}"
      turn_on:
        - service: rest_command.set_bedroom_fan_light
          data:
            light_percentage: 100
        - service: input_number.set_value
          data:
            entity_id: input_number.bedroom_fan_light
            value: 255
      turn_off:
        service: rest_command.turn_off_bedroom_fan_light