- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_can_1
    - light.living_room_can_2
    - light.living_room_can_3
    - light.living_room_can_4
    - light.living_room_fan_light