- id: '1590386707484'
  alias: Turn off Go to Sleep after 30 seconds
  description: ''
  trigger:
  - entity_id: input_boolean.go_to_sleep
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: '30'
  - data: {}
    entity_id: input_boolean.go_to_sleep
    service: input_boolean.turn_off
