homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include_dir_merge_named components/customizations

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

panel_iframe: !include components/panel.yaml

# Enables configuration UI
config:

# SSL Enabled using (Hass.io plugin - Duck DNS)
http:
  base_url: !secret ha_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: warning

# Enables a map showing the location of tracked devices
map:

# Cloud
cloud:

# https://www.home-assistant.io/components/system_health/
system_health:

sun:
  scan_interval: 60

# https://www.home-assistant.io/components/wwlln/
wwlln: 

# https://www.home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 14
  include:
    entities:
      - binary_sensor.patio_door
      - binary_sensor.washing_machine
      - calendar.appointments
      - climate.domain
      - device_tracker.lgwebostv
      - person.william
      - device_tracker.powerview_hub
      - device_tracker.august_lock
      - lock.august_lock
    domains:
      - light
      - media_player
      - sensor
  exclude:
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.installed_version
      - sensor.homeassistant
      - sensor.hassio_version
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state
      - sensor.kitchen_shade_position
      - sensor.kitchen_switch_battery
      - sensor.load_15m
      - sensor.load_1m
      - sensor.load_5m
      - sensor.main_shade_position
      - sensor.owm_weather_code
      - sensor.owm_wind_bearing
      - sensor.owm_wind_speed
      - sensor.pe_availability
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.rt_ac3100_bytes_received
      - sensor.rt_ac3100_bytes_sent
      - sensor.rt_ac3100_kbyte_sec_received
      - sensor.rt_ac3100_kbyte_sec_sent
      - sensor.rt_ac3100_packets_received
      - sensor.rt_ac3100_packets_sec_received
      - sensor.rt_ac3100_packets_sec_sent
      - sensor.rt_ac3100_kbyte_packets_sent
      - sensor.shade_positions
      - sensor.swap_use_percentage
      - sensor.washer_door_sensor
      - sensor.williams_iphone_battery_level
      - sensor.williams_iphone_battery_state

#######################################################################################
#                                                                                     #
#                       COMPONENTS                                                    #
#                                                                                     #
#######################################################################################
#######################################################################################
# Asus Router utilized for device_tracker
#
# https://www.home-assistant.io/components/asuswrt/
asuswrt:
  host: !secret router_ip_address
  username: !secret router_username
  password: !secret router_password
#######################################################################################


#######################################################################################
# HVAC system
#
# https://www.home-assistant.io/components/ecobee/
ecobee:
  api_key: !secret ecobee_api_key
#######################################################################################


#######################################################################################
# Binary sensors in Home Assistant
#
# https://www.home-assistant.io/components/binary_sensor/
binary_sensor: !include_dir_list components/binary_sensors
#######################################################################################


#######################################################################################
# Google Component - only used for calendar in Home Assistant
#
# https://www.home-assistant.io/components/calendar.google/
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
#######################################################################################


#######################################################################################
# Using IFTTT for quite a few components that support this more than home assistant
#
# https://www.home-assistant.io/components/ifttt/
ifttt:
  key: !secret ifttt_api_key
#######################################################################################


#######################################################################################
# Using IQVIA for the disease and allergy index
#
# https://www.home-assistant.io/components/iqvia/
iqvia:
  zip_code: !secret home_zipcode
  monitored_conditions:
    - allergy_average_forecasted
    - disease_average_forecasted
#######################################################################################    


#######################################################################################
# The input_boolean component allows the user to define boolean values that
# can be controlled via the frontend and can be used within conditions of
# automation. This can for example be used to disable or enable certain
# automations.
#
# https://www.home-assistant.io/components/input_boolean/
input_boolean: !include_dir_merge_named components/input_booleans
#######################################################################################


#######################################################################################
# Customized iOS push Notifications for Home Assistant / Node-Red
# TODO: File Structure
#
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:
  push:
    categories:
      - name: Home
        identifier: 'home'
        actions:
          - identifier: 'NO_MUSIC'
            title: 'Turn off music'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
          - identifier: 'RAISE_BLINDS'
            title: 'Raise Shades'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
      - name: Laundry Notification
        identifier: 'laundry'
        actions:
          - identifier: 'REMIND_ME_30'
            title: 'Remind me in 30 minutes'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
          - identifier: 'TELL_OTHER_PERSON'
            title: 'Ask them to do it'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
#######################################################################################

#######################################################################################
# Sensor information for Pi-Hole
# https://www.home-assistant.io/components/pi_hole/
pi_hole:
  host: !secret pi_hole_url
  ssl: false
  verify_ssl: false
#######################################################################################

#######################################################################################
# Allows connection of multiple device tracer entities to a single person
# 
# https://www.home-assistant.io/components/person/
person: !include_dir_merge_list people/
#######################################################################################


#######################################################################################
# Nest Components
# - smoke detector / CO detector
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
#######################################################################################


#######################################################################################
# Tracking all devices through Home Assistant
#  - Bluetooth
#  - Router
#  - GPS
# https://www.home-assistant.io/components/device_tracker/
device_tracker: !include components/device_tracker.yaml
#######################################################################################

#######################################################################################
# Life 360 component for reliable GPS location for the house (added in 0.95.0)
#
# https://deploy-preview-9539--home-assistant-docs.netlify.com/components/life360/
life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  driving_speed: 16
  max_update_wait:
    minutes: 40
#######################################################################################


#######################################################################################
# Media players in Home Assistant
#
# https://www.home-assistant.io/components/media_player/
media_player: !include_dir_merge_list components/media_players
#######################################################################################


#######################################################################################
# All custom scripts that do multiple actions with one call
#
# https://www.home-assistant.io/components/script
script: !include_dir_merge_named components/scripts
#######################################################################################


#######################################################################################
# All Sensors that are in Home Assistant
#
# https://www.home-assistant.io/components/sensor
sensor: !include_dir_merge_list components/sensors
#######################################################################################


#######################################################################################
# Speedtest.Net
#
# https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  scan_interval:
    minutes: 20
  monitored_conditions:
    - ping
    - download
    - upload
#######################################################################################


#######################################################################################
# Custom Switches in Home Assistant
#
# https://www.home-assistant.io/components/switch/
switch: !include_dir_merge_list components/switches
#######################################################################################


#######################################################################################
# Enables Wake on LAN domain
#
# https://www.home-assistant.io/components/wake_on_lan/
wake_on_lan:
#######################################################################################


#######################################################################################
# WeMo Plugs and Misc
#
# https://www.home-assistant.io/components/wemo/
wemo:
#######################################################################################


#######################################################################################
# Weather configuration in Home Assistant
#   Used for overall weather on lovelace page 
#
# https://www.home-assistant.io/components/weather/
weather: !include_dir_list components/weather
#######################################################################################


#######################################################################################
# Zones allow you to specify certain regions on earth (for now).
#
# https://www.home-assistant.io/components/zone/
#
zone: !include_dir_merge_list components/zones
#######################################################################################


#######################################################################################
# This handles my automations within Home Assistant
#   almost all my automations are handled within Node-Red
# https://www.home-assistant.io/docs/automation/
#
automation: !include_dir_merge_list components/automations
#######################################################################################


#######################################################################################
#
#                      NOT USED COMPONENTS
#
#######################################################################################
#Not Used
group:
scene: