- platform: wake_on_lan
  name: 'PC'
  mac: !secret razer_wired_mac_address
  host: !secret computer_ip_address
  turn_off:
    - service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: WIRED-RAZER