- platform: group
  name: Hallway Lights
  entities:
    - light.dividor_right
    - light.dividor_left
    # Custom Dual Can lights
    - light.entry_light_1
    - light.entry_light_2
    # Main Hallway lights
    - light.hallway_can_1
    - light.hallway_can_2
    - light.hallway_can_3
    - light.hallway_can_4
    - light.hallway_can_5