#####################################################
#                                                   #
#           ReST Sensors                            #
# https://www.home-assistant.io/integrations/rest/  #
#                                                   #
#####################################################
- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/stable.json
  name: Latest HomeAssistant Version
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 3600  

- platform: rest
  resource: !secret hunter_douglas_hub_rest_url
  name: Shade Positions
  json_attributes:
    - shadeData
  value_template: "{{ value_json.value }}"
  scan_interval: 15

- platform: rest
  resource: !secret get_cloud_coverage_url
  name: owm_cloud_coverage
  value_template: '{{ value_json.clouds.all }}'
  scan_interval: 600