- platform: template
  sensors:
    sensor_count:
      friendly_name: 'Number of Sensors'
      value_template: >
        {%- set domains = ['sensor'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    lights_count:
      friendly_name: 'Number of Lights'
      value_template: >
        {%- set domains = ['light'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    main_shade_position:
      friendly_name: Main Shade Position
      icon_template: mdi:blinds
      value_template: >
        {% if states.sensor.shade_positions.attributes.shadeData[1].positions.position1 == 65535 %}
          Open
        {% elif states.sensor.shade_positions.attributes.shadeData[1].positions.position1 == 0 %}
          Closed
        {% else %}
          {{ ((1 - (states.sensor.shade_positions.attributes.shadeData[1].positions.position1 / 65535)) * 100) | round(0) }}%
        {% endif %}
    kitchen_shade_position:
      friendly_name: Kitchen Shade Position
      icon_template: mdi:blinds
      value_template: >
        {% if states.sensor.shade_positions.attributes.shadeData[0].positions.position1 == 65535 %}
          Open
        {% elif states.sensor.shade_positions.attributes.shadeData[0].positions.position1 == 0 %}
          Closed
        {% else %}
          {{ ((1 - (states.sensor.shade_positions.attributes.shadeData[0].positions.position1 / 65535)) * 100) | round(0) }}%
        {% endif %}
    wind_speed_knots:
      friendly_name: Wind Speed
      icon_template: mdi:weather-windy
      unit_of_measurement: knots
      value_template: >
        {% set result = float(states("sensor.owm_wind_speed")) * 1.94384 %}
        {{ result | round() }}
    github_stargazers:
      friendly_name: HomeAssistant Stars
      icon_template: mdi:github-circle
      value_template: >
        {{ state_attr("sensor.homeassistant", "stargazers") }}
    closet_motion_sensor_battery:
      friendly_name: "Closet Motion Sensor Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("binary_sensor.closet_motion_sensor", "battery") }}
      icon_template: >-
        {%- if is_state("states.binary_sensor.closet_motion_sensor.attributes.battery", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("binary_sensor.closet_motion_sensor", "battery") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("binary_sensor.closet_motion_sensor", "battery") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("binary_sensor.closet_motion_sensor", "battery") | float / 10 | round * 10}}
        {%- endif %}
    laundry_motion_sensor_battery:
      friendly_name: "Laundry Motion Sensor Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("binary_sensor.laundry_motion_motion_sensor", "battery") }}
      icon_template: >-
        {%- if is_state("states.binary_sensor.laundry_motion_motion_sensor.attributes.battery", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("binary_sensor.laundry_motion_motion_sensor", "battery") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("binary_sensor.laundry_motion_motion_sensor", "battery") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("binary_sensor.laundry_motion_motion_sensor", "battery") | float / 10 | round * 10}}
        {%- endif %}
    utility_motion_sensor_battery:
      friendly_name: "Utility Room Motion Sensor Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("binary_sensor.utility_room_motion_sensor", "battery") }}
      icon_template: >-
        {%- if is_state("states.binary_sensor.utility_room_motion_sensor.attributes.battery", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("binary_sensor.utility_room_motion_sensor", "battery") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("binary_sensor.utility_room_motion_sensor", "battery") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("binary_sensor.utility_room_motion_sensor", "battery") | float / 10 | round * 10}}
        {%- endif %}
    hallway_switch_battery:
      friendly_name: "Hallway Switch Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("sensor.hallway_switch", "battery") }}
      icon_template: >-
        {%- if is_state("states.sensor.hallway_switch.attributes.battery", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("sensor.hallway_switch", "battery") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("sensor.hallway_switch", "battery") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("sensor.hallway_switch", "battery") | float / 10 | round * 10}}
        {%- endif %}
    bedroom_switch_battery:
      friendly_name: "Bedroom Switch Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("sensor.bedroom_switch", "battery") }}
      icon_template: >-
        {%- if is_state("states.sensor.bedroom_switch.attributes.battery", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("sensor.bedroom_switch", "battery") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("sensor.bedroom_switch", "battery") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("sensor.bedroom_switch", "battery") | float / 10 | round * 10}}
        {%- endif %}
    kitchen_switch_battery:
      friendly_name: "Kitchen Switch Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("sensor.kitchen_switch", "battery") }}
      icon_template: >-
        {%- if is_state("states.sensor.kitchen_switch.attributes.battery", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("sensor.kitchen_switch", "battery") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("sensor.kitchen_switch", "battery") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("sensor.kitchen_switch", "battery") | float / 10 | round * 10}}
        {%- endif %}
    august_lock_battery:
      friendly_name: "August Lock Battery"
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("zwave.august_asl_03_smart_lock_2", "battery_level") }}
      icon_template: >-
        {%- if is_state("states.zwave.august_asl_03_smart_lock_2.attributes.battery_level", "unknown") %}
          mdi:battery-unknown
        {% elif state_attr("zwave.august_asl_03_smart_lock_2", "battery_level") | float <= 5 %}
          mdi:battery-outline
        {% elif state_attr("zwave.august_asl_03_smart_lock_2", "battery_level") | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{state_attr("zwave.august_asl_03_smart_lock_2", "battery_level") | float / 10 | round * 10}}
        {%- endif %}