##############################################
#                                            #
#               VERSION                      #
#                                            #
##############################################
- platform: version
  name: Installed Version