#########################################################
#                                                       #
#               VERSION                                 #
# https://www.home-assistant.io/integrations/version/   #
#                                                       #
#########################################################
- platform: version
  name: Installed Version