##################################################################
#                                                                #
#                    Waze Travel times                           #
# https://www.home-assistant.io/integrations/waze_travel_time/   #
#                                                                #
##################################################################
- platform: waze_travel_time
  name: Work Travel Time
  origin: !secret home_address
  destination: !secret work_address
  region: 'US'
- platform: waze_travel_time
  name: !secret main_airport_name
  origin: !secret home_address
  destination: !secret airport_address
  region: 'US'